<?php
return  [
    'default' => 'mysql',
    'connections' => [
        'mysql' => [
            'driver'      => 'mysql',
            'host'        => '127.0.0.1',
            'port'        => '3306',
            'database'    => 'xucheng_admin',
            'username'    => 'xihe',
            'password'    => 'xohe4567',
            'charset'     => 'utf8mb4',
            'collation'   => 'utf8mb4_general_ci',
            'prefix'      => '',
            'strict'      => true,
            'engine'      => null,
        ],
        'mysql2' => [
            'driver'      => 'mysql',
            'host'        => '192.168.0.44',
            'port'        => '3306',
            'database'    => 'xucheng_admin',
            'username'    => 'xucheng002',
            'password'    => '8IT[eC]Cy-kTt3U4',
            'charset'     => 'utf8mb4',
            'collation'   => 'utf8mb4_general_ci',
            'prefix'      => '',
            'strict'      => true,
            'engine'      => null,
        ],
        'wukong' => [
            'driver'      => 'mysql',
            'host'        => '211.149.172.164',
            'port'        => '3306',
            'database'    => 'liujifen822',
            'username'    => 'liujifen822',
            'password'    => 'JtcKKmkyA7fzyLRP',
            'charset'     => 'utf8mb4',
            'collation'   => 'utf8mb4_general_ci',
            'prefix'      => '',
            'strict'      => true,
            'engine'      => null,
        ],
    ],
];